DROP DATABASE IF EXISTS DigitalBeats;
CREATE DATABASE DigitalBeats;
USE DigitalBeats;

CREATE TABLE USUARIOS (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    TELEFONO INT NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL UNIQUE,
    FECHA_NACIMIENTO DATE NOT NULL,
    ADMIN BOOLEAN NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    CATEGORIA_PADRE INT,
    FOREIGN KEY (CATEGORIA_PADRE) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(2000) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    PRECIO_DESCUENTO DECIMAL(10,2),
    CARACTERISTICAS VARCHAR(500) NOT NULL,
    DESTACADO BOOLEAN NOT NULL,
    NOVEDAD BOOLEAN NOT NULL,
    VECES_VENDIDO INT NOT NULL DEFAULT 0,
    FOTO VARCHAR(255) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_HORA DATETIME NOT NULL,
    FECHA_ENTREGA DATE NOT NULL,
    DIRECCION VARCHAR(255) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ESTADO ENUM('Entregado', 'En reparto', 'Procesando') NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIOS(ID_CLIENTE)
);

CREATE TABLE LINEA_PEDIDO (
    ID_LINEA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNIDAD DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE OPINIONES (
    ID_OPINION INT PRIMARY KEY AUTO_INCREMENT,
    VALORACION INT CHECK (VALORACION BETWEEN 1 AND 10),
    FECHA_HORA DATETIME NOT NULL,
    COMENTARIO VARCHAR(300),
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIOS(ID_CLIENTE),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE MENSAJES (
    ID_MENSAJE INT PRIMARY KEY AUTO_INCREMENT,
    CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(1500) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    MOTIVO_CONTACTO VARCHAR(255) NOT NULL,
    NUMERO_PEDIDO INT
);